[package]
name = "lirix"
version = "0.2.0-SNAPSHOT"
authors = ["Bora Kaplan <kaplanbora@protonmail.com>"]
edition = "2018"

[dependencies]
mpris = "1.1.1"
failure = "0.1.2"
reqwest = "0.9.9"
regex = "1.1.0"
dirs = "1.0.5"
